name: lemon_markets_client
description: Simple client to access lemonMarkets API
version: 0.1.0
homepage: https://github.com/stormqueen23/lemonMarketClient

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  test: ^1.19.3

  build_runner: ^2.1.5
  json_serializable: ^6.0.1

flutter: