name: lemon_markets_client
description: Simple client to access lemonMarkets API
version: 0.1.0
author: Melanie Siekmöller
homepage: https://github.com/stormqueen23/lemonMarketClient

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.1
  http: ^0.13.3
  json_annotation: ^4.0.0


dev_dependencies:
  test: ^1.17.12

  build_runner: ^2.0.2
  json_serializable: ^4.0.3
flutter: